# syntax=docker/dockerfile:1
FROM python:3.8.18-alpine
WORKDIR /app
RUN apk add --no-cache gcc musl-dev linux-headers
# RUN pip install --upgrade pip
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
COPY . .
RUN touch backend.sock
CMD ["sh", "-c", "uwsgi --ini uwsgi.ini"]
