version: '3.9'
services:
  nginx:
    build:
      dockerfile: dockerfile.nginx
    ports:
    - '8000:8000'
    depends_on:
      - backend
  backend:
    build:
      dockerfile: dockerfile.backend
    environment:
    - DATABASE_HOST=${DATABASE_HOST}
    - DATABASE_PORT=${DATABASE_PORT}
    - DATABASE_USER=${DATABASE_USER}
    - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    - DATABASE_NAME=${DATABASE_NAME}
    - REDIS_HOST=${REDIS_HOST}
    - REDIS_PORT=${REDIS_PORT}
    ports:
    - '8001:8001'
    volumes:
      - ${BACKEND_VOLUME}:/app
    depends_on:
    - db
    - redis
  db:
    image: postgres:14.10
    environment:
    - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ${DATABASE_VOLUME}:/var/lib/postgresql/data
    ports:
    - '5432:5432'
  redis:
    image: redis:7.2.3-alpine
    ports:
    - '6379:6379'
